export const mockUsers = [
    {
      id: "1",
      name: "Rocket Raccoon",
      email: "john@example.com",
      avatar: "https://konachan.net/image/219bc0c7cd94fc7b388e7646e416e011/Konachan.com%20-%20389912%20barefoot%20black_hair%20blue_archive%20blush%20chinese_dress%20dress%20gray_eyes%20halo%20long_hair%20momobug22%20red%20ryuuge_kisaki%20signed%20twintails%20watermark.jpg",
      role: "admin",
      perms: ["admin", "user", "guest"],
    },
    {
      id: "2",
      name: "Tony Stark",
      email: "tony@starkindustries.com",
      avatar: "https://i.pravatar.cc/150?img=5",
      role: "user",
      perms: ["user"],
    },
    {
      id: "3",
      name: "Natasha Romanoff",
      email: "natasha@shield.com",
      avatar: "https://i.pravatar.cc/150?img=12",
      role: "moderator",
      perms: ["user", "guest"],
    },
    {
      id: "4",
      name: "Steve Rogers",
      email: "cap@avengers.com",
      avatar: "https://i.pravatar.cc/150?img=1",
      role: "admin",
      perms: ["admin", "user"],
    },
    {
      id: "5",
      name: "Bruce Banner",
      email: "bruce@science.org",
      avatar: "https://i.pravatar.cc/150?img=8",
      role: "user",
      perms: ["user", "guest"],
    },
    {
      id: "6",
      name: "Peter Parker",
      email: "spidey@nyc.com",
      avatar: "https://i.pravatar.cc/150?img=3",
      role: "guest",
      perms: ["guest"],
    },
    {
      id: "7",
      name: "Wanda Maximoff",
      email: "wanda@avengers.com",
      avatar: "https://i.pravatar.cc/150?img=6",
      role: "admin",
      perms: ["admin", "user", "guest"],
    },
  ];
  